In [1]:
import pandas as pd
from datetime import datetime as dt
from pandas.io import gbq
import numpy as np
from shapely.geometry import Point, LineString
from geopandas import GeoDataFrame
import geopandas as gpd

In [2]:
project_id = 'crafty-water-184820'

In [3]:
all_data_query = """
SELECT *
FROM
  [crafty-water-184820:NYC_trip_data.all_data]
"""

In [4]:
all_data_df = gbq.read_gbq(all_data_query, project_id=project_id)

ImportError: Load data from Google BigQuery

the pandas-gbq package is not installed
see the docs: https://pandas-gbq.readthedocs.io

you can install via pip or conda:
pip install pandas-gbq
conda install pandas-gbq -c conda-forge

In [123]:
df = all_data_df.copy()

In [124]:
df[(df['pickup_longitude'] == 0) | (df['dropoff_longitude'] == 0)]

,pickup_datetime,dropoff_datetime,trip_distance,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude
427,2015-03-10 22:48:12,2015-03-10 22:48:12,0.00,-73.937782,40.812679,0.000000,0.000000
527,2015-04-18 23:15:21,2015-04-18 23:27:33,3.20,-73.943207,40.692310,0.000000,0.000000
1742,2015-09-07 16:16:55,2015-09-07 16:17:27,0.00,0.000000,0.000000,0.000000,0.000000
2067,2015-08-07 23:19:37,2015-08-07 23:26:00,0.90,0.000000,0.000000,-73.966339,40.690468
2430,2015-05-16 07:38:40,2015-05-16 07:38:42,0.00,0.000000,0.000000,-73.937645,40.758148
4212,2015-06-12 16:34:03,2015-06-12 16:34:33,0.70,0.000000,0.000000,-73.948555,40.808548
4668,2015-11-30 06:50:12,2015-11-30 06:52:26,0.50,0.000000,0.000000,-73.957542,40.717770
5701,2015-04-23 07:52:01,2015-04-23 07:52:01,0.00,0.000000,0.000000,-73.902748,40.838757
5983,2015-09-28 08:45:39,2015-09-28 08:52:57,1.50,0.000000,0.000000,-73.953270,40.807217
6930,2015-04-07 10:23:33,2015-04-07 10:47:33,2.67,-73.933144,40.758507,0.000000,0.000000
7124,2015-01-19 14:33:22,2015-01-19 14:50:24,6.06,0.000000,0.000000,0.000000,0.000000
7356,2015-05-26 17:02:30,2015-05-26 17:02:32,0.00,0.000000,0.000000,-73.875839,40.677048
9107,2015-04-11 13:49:49,2015-04-11 14:20:42,5.50,0.000000,0.000000,-74.004219,40.749619
9344,2015-08-03 10:04:03,2015-08-03 10:31:10,5.37,-73.957367,40.690926,0.000000,0.000000
9346,2015-04-23 13:40:49,2015-04-23 13:43:23,0.00,0.000000,0.000000,-73.893150,40.846802
9485,2015-03-04 13:18:19,2015-03-04 13:18:19,0.00,-73.891029,40.766579,0.000000,0.000000
9889,2015-06-21 13:36:13,2015-06-21 13:36:13,0.00,-73.873405,40.748859,0.000000,0.000000
10179,2015-07-20 20:04:27,2015-07-20 20:04:36,0.00,0.000000,0.000000,0.000000,0.000000
10408,2015-09-16 18:13:44,2015-09-16 18:13:56,0.00,0.000000,0.000000,-73.931213,40.665218
10733,2015-09-13 01:41:38,2015-09-13 01:41:38,0.00,-73.933235,40.586567,0.000000,0.000000
10859,2015-10-15 12:57:37,2015-10-15 13:00:15,0.40,0.000000,0.000000,-73.953896,40.808556
12453,2015-01-04 17:08:18,2015-01-04 17:20:35,3.04,0.000000,0.000000,0.000000,0.000000
12972,2015-06-08 19:31:57,2015-06-08 19:41:26,2.00,-73.950645,40.668587,0.000000,0.000000
13322,2015-09-11 13:41:19,2015-09-11 13:42:13,0.00,0.000000,0.000000,-73.938728,40.674671
13783,2015-09-14 17:07:13,2015-09-14 17:08:02,0.00,0.000000,0.000000,-73.865387,40.878761
14597,2015-02-26 09:48:39,2015-02-26 10:19:39,3.79,-73.953018,40.728222,0.000000,0.000000
14813,2015-09-19 06:21:21,2015-09-19 06:32:49,2.81,0.000000,0.000000,0.000000,0.000000
14925,2015-11-19 19:08:05,2015-11-19 19:08:05,0.00,-73.891075,40.862057,0.000000,0.000000
15305,2015-01-28 12:16:59,2015-01-28 12:27:54,2.30,0.000000,0.000000,-73.964890,40.806488
15978,2015-02-05 08:55:34,2015-02-05 08:55:34,0.00,-73.947296,40.631596,0.000000,0.000000
...,...,...,...,...,...,...,...
1989482,2015-06-13 21:46:01,2015-06-13 21:52:45,1.20,-73.981949,40.662537,0.000000,0.000000
1990114,2015-01-08 08:00:38,2015-01-08 09:43:38,13.05,-73.926369,40.693062,0.000000,0.000000
1990418,2015-03-16 17:49:43,2015-03-16 18:19:03,6.20,0.000000,0.000000,-73.990685,40.743790
1990495,2015-10-15 03:06:27,2015-10-15 03:15:04,1.50,0.000000,0.000000,-73.908875,40.694584
1990580,2015-04-25 21:48:22,2015-04-25 21:48:22,0.00,-73.925446,40.684589,0.000000,0.000000
1990617,2015-03-25 09:48:16,2015-03-25 09:48:17,0.00,0.000000,0.000000,-73.836975,40.839573
1990819,2015-08-25 03:01:24,2015-08-25 03:18:24,4.01,-73.955544,40.804478,0.000000,0.000000
1991770,2015-02-06 23:17:13,2015-02-06 23:25:24,1.17,-73.954308,40.790676,0.000000,0.000000
1991970,2015-07-03 14:42:52,2015-07-03 15:01:29,4.80,0.000000,0.000000,-73.942810,40.711075
1992052,2015-02-02 00:18:11,2015-02-02 00:18:36,4.36,-73.915558,40.757309,0.000000,0.000000
1992070,2015-03-21 05:38:03,2015-03-21 05:38:04,0.00,0.000000,0.000000,-73.751274,40.708931
1992486,2015-07-10 19:18:40,2015-07-10 19:33:40,3.87,-73.890022,40.860798,0.000000,0.000000
1992887,2015-02-22 14:19:18,2015-02-22 14:19:18,0.00,-73.939713,40.815681,0.000000,0.000000
1993229,2015-09-06 14:56:25,2015-09-06 15:37:37,18.60,0.000000,0.000000,-73.782242,40.644257
1994122,2015-10-25 21:55:20,2015-10-25 21:55:22,0.00,0.000000,0.000000,-73.934593,40.852196
1994589,2015-04-15 21:13:20,2015-04-15 21:18:34,0.70,0.000000,0.000000,-73.956711,40.718845
1995101,2015-10-08 04:17:12,2015-10-08 04:17:13,0.00,0.000000,0.000000,-73.892509,40.816254
1995898,2015-01-24 20:02:16,2015-01-24 20:03:39,0.07,0.000000,0.000000,0.000000,0.000000
1996260,2015-12-26 12:59:19,2015-12-26 12:59:21,0.00,0.000000,0.000000,-73.879372,40.873966
1996262,2015-02-17 15:55:17,2015-02-17 15:55:19,0.00,0.000000,0.000000,-73.955582,40.814007
1996443,2015-05-01 23:22:27,2015-05-01 23:22:27,0.00,-73.919868,40.843586,0.000000,0.000000
1996515,2015-06-12 18:26:20,2015-06-12 18:33:54,1.30,0.000000,0.000000,-73.946388,40.806725
1997144,2015-10-16 14:42:26,2015-10-16 14:42:27,0.00,0.000000,0.000000,-73.956024,40.803520
1997280,2015-07-01 09:28:46,2015-07-01 09:28:46,0.00,-73.949417,40.802364,0.000000,0.000000
1998238,2015-01-13 09:16:29,2015-01-13 09:21:29,0.84,-73.950195,40.826878,0.000000,0.000000
1998454,2015-01-10 17:50:46,2015-01-10 17:50:46,0.00,-73.919548,40.807823,0.000000,0.000000
1998640,2015-10-19 14:22:01,2015-10-19 14:25:22,0.00,0.000000,0.000000,-73.930496,40.675076
1998741,2015-12-13 05:22:30,2015-12-13 06:04:17,11.20,0.000000,0.000000,-73.969589,40.793873
1999707,2015-09-05 01:06:13,2015-09-05 01:18:23,1.60,0.000000,0.000000,-73.923500,40.684860
1999829,2015-01-18 20:28:00,2015-01-18 20:28:01,0.02,0.000000,0.000000,-73.864349,40.683830

In [125]:
df = df[(df['pickup_longitude'] != 0) & (df['dropoff_longitude'] != 0)]

In [126]:
df[(df['pickup_longitude'] == df['dropoff_longitude']) & (df['pickup_latitude'] == df['dropoff_latitude'])]

,pickup_datetime,dropoff_datetime,trip_distance,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude
2711,2015-07-25 02:50:18,2015-07-25 02:50:38,0.9,-73.739929,40.633835,-73.739929,40.633835
3399,2015-03-21 19:56:03,2015-03-21 19:56:24,16.6,-73.912834,40.848560,-73.912834,40.848560
5552,2015-12-27 07:24:37,2015-12-27 07:24:45,0.5,-73.944786,40.819057,-73.944786,40.819057
5754,2015-09-18 00:39:41,2015-09-18 00:39:44,4.6,-73.924080,40.770058,-73.924080,40.770058
5859,2015-02-27 22:18:41,2015-02-27 22:18:49,0.0,-73.949776,40.813904,-73.949776,40.813904
6676,2015-12-22 13:29:50,2015-12-22 13:30:06,0.0,-73.934799,40.634892,-73.934799,40.634892
7432,2015-06-24 22:23:52,2015-06-24 22:23:57,10.4,-73.763672,40.594021,-73.763672,40.594021
7436,2015-02-20 21:13:27,2015-02-20 21:13:37,0.7,-73.858292,40.821659,-73.858292,40.821659
7703,2015-06-30 15:48:31,2015-06-30 15:48:40,7.0,-73.927353,40.862427,-73.927353,40.862427
8044,2015-01-23 13:46:49,2015-01-23 13:46:55,0.0,-73.772667,40.764912,-73.772667,40.764912
8081,2015-06-23 16:52:14,2015-06-23 16:52:54,1.5,-73.925041,40.846569,-73.925041,40.846569
9891,2015-09-01 15:41:15,2015-09-01 15:41:26,0.0,-73.911934,40.669548,-73.911934,40.669548
10404,2015-09-05 09:21:02,2015-09-05 09:21:05,0.0,-73.945442,40.751427,-73.945442,40.751427
10989,2015-08-10 14:05:31,2015-08-10 14:05:53,3.4,-74.001785,40.655514,-74.001785,40.655514
11137,2015-06-02 18:57:21,2015-06-02 18:57:32,0.0,-73.954971,40.799683,-73.954971,40.799683
13323,2015-12-14 08:41:56,2015-12-14 08:42:18,0.0,-73.945541,40.751575,-73.945541,40.751575
13418,2015-11-15 23:06:47,2015-11-15 23:07:03,4.9,-73.928658,40.835850,-73.928658,40.835850
13819,2015-12-06 14:34:40,2015-12-06 14:34:48,0.0,-73.912163,40.600899,-73.912163,40.600899
13862,2015-01-20 22:00:32,2015-01-20 22:00:42,0.0,-73.924393,40.650845,-73.924393,40.650845
14028,2015-11-06 13:50:22,2015-11-06 13:50:34,0.0,-73.902695,40.870689,-73.902695,40.870689
14710,2015-02-10 10:58:34,2015-02-10 10:59:04,3.0,-73.819649,40.826473,-73.819649,40.826473
16452,2015-08-11 18:15:53,2015-08-11 18:16:01,0.0,-73.853157,40.852718,-73.853157,40.852718
16626,2015-02-22 23:56:43,2015-02-22 23:57:00,0.0,-73.858986,40.737331,-73.858986,40.737331
17537,2015-05-31 01:43:57,2015-05-31 01:44:10,0.2,-73.886414,40.882568,-73.886414,40.882568
17855,2015-11-22 14:05:24,2015-11-22 14:05:28,5.6,-73.977951,40.684685,-73.977951,40.684685
18012,2015-06-01 07:21:31,2015-06-01 07:21:39,3.9,-73.937721,40.679768,-73.937721,40.679768
20165,2015-06-30 22:06:21,2015-06-30 22:06:35,0.1,-73.910957,40.880421,-73.910957,40.880421
21734,2015-03-31 12:19:00,2015-03-31 12:19:15,2.8,-73.923447,40.743198,-73.923447,40.743198
22760,2015-11-15 03:57:52,2015-11-15 03:58:05,0.0,-73.955040,40.639748,-73.955040,40.639748
23202,2015-09-06 09:38:47,2015-09-06 09:38:50,0.0,-73.932785,40.673416,-73.932785,40.673416
...,...,...,...,...,...,...,...
1979108,2015-08-20 08:41:41,2015-08-20 08:41:43,0.0,-73.987808,40.672440,-73.987808,40.672440
1979364,2015-07-19 19:27:50,2015-07-19 19:27:54,0.0,-73.823898,40.824055,-73.823898,40.824055
1979997,2015-03-17 06:49:55,2015-03-17 06:50:02,0.8,-73.906532,40.846203,-73.906532,40.846203
1980320,2015-08-22 02:27:56,2015-08-22 02:28:11,13.0,-74.015411,40.603024,-74.015411,40.603024
1980738,2015-09-01 05:44:54,2015-09-01 05:44:58,0.0,-73.846619,40.684559,-73.846619,40.684559
1980769,2015-07-09 17:45:13,2015-07-09 17:45:28,5.9,-73.946815,40.744629,-73.946815,40.744629
1981395,2015-05-01 01:23:00,2015-05-01 01:23:03,1.0,-73.899841,40.814323,-73.899841,40.814323
1981402,2015-12-03 09:54:36,2015-12-03 09:56:40,0.0,-73.867775,40.736477,-73.867775,40.736477
1981689,2015-09-30 21:58:57,2015-09-30 21:58:58,0.0,-73.903275,40.859043,-73.903275,40.859043
1981736,2015-01-02 17:25:46,2015-01-02 17:26:01,4.2,-73.923439,40.670143,-73.923439,40.670143
1982037,2015-05-21 02:03:09,2015-05-21 02:03:12,0.0,-73.860909,40.819504,-73.860909,40.819504
1982594,2015-12-29 19:48:32,2015-12-29 19:48:34,0.0,-73.943176,40.706722,-73.943176,40.706722
1983325,2015-12-09 20:46:00,2015-12-09 20:46:16,5.4,-73.946648,40.695686,-73.946648,40.695686
1983708,2015-11-17 03:06:09,2015-11-17 03:06:36,0.5,-73.875237,40.746849,-73.875237,40.746849
1985446,2015-07-24 00:01:41,2015-07-24 00:01:46,0.0,-73.981194,40.575729,-73.981194,40.575729
1986784,2015-09-30 09:36:25,2015-09-30 09:36:29,1.9,-73.905602,40.773182,-73.905602,40.773182
1987582,2015-06-04 17:29:27,2015-06-04 17:29:50,11.9,-73.912491,40.601479,-73.912491,40.601479
1987858,2015-10-25 03:46:30,2015-10-25 03:47:09,2.8,-73.912025,40.851353,-73.912025,40.851353
1988042,2015-07-24 11:03:27,2015-07-24 11:03:40,2.4,-73.929344,40.678574,-73.929344,40.678574
1988591,2015-10-19 16:17:13,2015-10-19 16:20:02,5.7,-73.948845,40.828415,-73.948845,40.828415
1990776,2015-06-27 15:52:44,2015-06-27 15:53:08,1.2,-73.946167,40.832130,-73.946167,40.832130
1993129,2015-08-15 16:23:15,2015-08-15 16:23:26,0.0,-73.937340,40.759319,-73.937340,40.759319
1993520,2015-04-03 05:05:15,2015-04-03 05:05:18,0.0,-73.918175,40.781155,-73.918175,40.781155
1993908,2015-12-04 01:56:01,2015-12-04 01:56:19,2.0,-73.816093,40.683903,-73.816093,40.683903
1994586,2015-10-15 11:10:23,2015-10-15 11:10:54,0.0,-73.919525,40.622707,-73.919525,40.622707
1995119,2015-04-25 17:54:42,2015-04-25 17:54:44,8.4,-73.884193,40.712284,-73.884193,40.712284
1995788,2015-09-16 10:06:31,2015-09-16 10:06:45,1.0,-73.956650,40.723091,-73.956650,40.723091
1996123,2015-09-22 20:17:11,2015-09-22 20:18:23,0.0,-73.936699,40.764805,-73.936699,40.764805
1998176,2015-12-03 07:39:28,2015-12-03 07:39:32,1.5,-73.940903,40.794933,-73.940903,40.794933
1999369,2015-06-26 22:42:50,2015-06-26 22:43:13,2.3,-73.946815,40.632130,-73.946815,40.632130

In [127]:
df = df[(df['pickup_longitude'] != df['dropoff_longitude']) & (df['pickup_latitude'] != df['dropoff_latitude'])]

In [128]:
df[df.pickup_datetime > df.dropoff_datetime]

,pickup_datetime,dropoff_datetime,trip_distance,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude
12169,2015-11-01 01:57:00,2015-11-01 01:08:19,2.20,-73.983597,40.676373,-73.956856,40.673985
19773,2015-11-01 01:47:21,2015-11-01 01:03:20,9.00,-73.945236,40.808105,-73.866158,40.871876
25391,2015-11-01 01:57:05,2015-11-01 01:14:08,6.90,-73.963150,40.693687,-74.014175,40.650024
148424,2015-11-01 01:41:23,2015-11-01 01:10:18,7.00,-73.948097,40.711163,-74.002243,40.649418
427657,2014-05-31 23:44:00,2014-05-31 00:17:00,10.98,-73.843636,40.755981,-73.986115,40.718037
703358,2015-11-01 01:45:59,2015-11-01 01:07:00,8.40,-73.992828,40.715179,-74.019989,40.649738
794324,2015-11-01 01:38:35,2015-11-01 01:02:12,4.40,-74.014153,40.709530,-73.957657,40.681408
844689,2015-11-01 01:48:27,2015-11-01 01:01:04,2.30,-73.985077,40.768726,-73.977310,40.745380
1075094,2015-11-01 01:57:51,2015-11-01 01:16:20,2.10,-73.983391,40.749756,-73.983009,40.727001
1107248,2015-11-01 01:59:20,2015-11-01 01:09:52,1.80,-73.946236,40.703251,-73.942879,40.720814
1141518,2015-11-01 01:55:10,2015-11-01 01:02:19,1.30,-73.981644,40.758835,-73.985184,40.743755
1228511,2015-11-01 01:59:43,2015-11-01 01:22:41,3.90,-73.932411,40.848740,-73.905273,40.816132
1250597,2015-11-01 01:53:47,2015-11-01 01:08:33,2.80,-73.951889,40.725521,-73.922081,40.700226
1253568,2015-11-01 01:45:01,2015-11-01 01:00:23,3.30,-73.981750,40.679173,-73.991943,40.722527
1258088,2015-11-01 01:48:27,2015-11-01 01:05:57,3.70,-73.880470,40.756153,-73.823402,40.755314
1265454,2015-11-01 01:52:05,2015-11-01 01:11:42,4.20,-73.952774,40.726913,-73.902138,40.694164
1378743,2014-06-23 23:58:00,2014-06-23 00:02:00,1.36,-73.870979,40.733250,-73.877335,40.719749
1437500,2014-11-02 01:59:41,2014-11-02 01:40:04,15.10,-73.903954,40.774666,-73.940323,40.611164
1448562,2014-11-02 01:55:36,2014-11-02 01:35:07,11.40,-73.946419,40.692078,-73.949066,40.781452
1493482,2014-11-02 01:59:00,2014-11-02 01:15:51,5.30,-73.957916,40.719883,-73.953842,40.770947
1565485,2014-11-02 01:51:05,2014-11-02 01:02:59,4.80,-73.843948,40.721012,-73.882843,40.755939
1589954,2014-11-02 01:58:53,2014-11-02 01:14:52,2.60,-73.961655,40.713806,-73.922424,40.709023
1840329,2015-11-01 01:49:36,2015-11-01 01:12:09,3.60,-73.987030,40.736465,-73.979790,40.688408
1926153,2015-11-01 01:59:21,2015-11-01 01:07:58,1.20,-73.986542,40.702431,-73.983818,40.692181
1963725,2015-11-01 01:44:25,2015-11-01 01:09:38,10.40,-73.952919,40.714046,-74.001778,40.622379

In [129]:
df['pickup_datetime_new'] = df['pickup_datetime']
mask = (df.dropoff_datetime < df.pickup_datetime) & (pd.DatetimeIndex(df['pickup_datetime']).hour != 23)
df.loc[mask, 'pickup_datetime_new'] = df.loc[mask, 'pickup_datetime_new'] - pd.Timedelta(hours=1)

In [132]:
df[(pd.DatetimeIndex(df['pickup_datetime_new']).hour == 23) & (pd.DatetimeIndex(df['dropoff_datetime']).hour == 0)]

,pickup_datetime,dropoff_datetime,trip_distance,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,pickup_datetime_new
66,2015-05-23 23:44:42,2015-05-24 00:01:00,2.75,-73.959061,40.718563,-73.933380,40.702984,2015-05-23 23:44:42
341,2015-11-26 23:55:05,2015-11-27 00:00:41,1.31,-73.954834,40.805244,-73.949928,40.822014,2015-11-26 23:55:05
353,2015-02-26 23:56:40,2015-02-27 00:17:29,3.91,-73.958153,40.721840,-73.914474,40.687462,2015-02-26 23:56:40
410,2015-03-28 23:41:28,2015-03-29 00:06:49,6.14,-73.980194,40.660526,-73.959785,40.577995,2015-03-28 23:41:28
671,2015-04-18 23:39:39,2015-04-19 00:32:32,6.81,-73.957603,40.722237,-73.968178,40.759277,2015-04-18 23:39:39
699,2015-12-18 23:59:49,2015-12-19 00:02:15,0.00,-74.000542,40.593769,-74.000488,40.594418,2015-12-18 23:59:49
958,2015-10-23 23:56:51,2015-10-24 00:01:24,0.56,-73.967026,40.683506,-73.975563,40.686710,2015-10-23 23:56:51
1014,2015-01-09 23:59:38,2015-01-10 00:12:49,2.91,-73.939774,40.790024,-73.936638,40.822327,2015-01-09 23:59:38
1072,2015-05-03 23:58:06,2015-05-04 00:06:14,1.63,-73.883553,40.747673,-73.860733,40.756065,2015-05-03 23:58:06
1076,2015-12-18 23:51:33,2015-12-19 00:06:48,3.15,-73.952080,40.732510,-73.923264,40.706806,2015-12-18 23:51:33
1227,2015-07-28 23:59:05,2015-07-29 00:15:27,2.84,-73.940872,40.841572,-73.945351,40.807594,2015-07-28 23:59:05
1242,2015-07-18 23:20:10,2015-07-19 00:03:23,8.70,-73.931351,40.697437,-73.951683,40.773449,2015-07-18 23:20:10
1256,2015-04-17 23:49:52,2015-04-18 00:16:42,3.19,-73.964462,40.711433,-73.992729,40.737377,2015-04-17 23:49:52
1290,2015-11-23 23:46:10,2015-11-24 00:13:29,8.12,-73.977165,40.683559,-73.988274,40.778042,2015-11-23 23:46:10
1297,2015-02-18 23:52:51,2015-02-19 00:09:37,2.53,-73.977722,40.687706,-73.996803,40.716507,2015-02-18 23:52:51
1343,2015-02-01 23:19:58,2015-02-02 00:29:04,22.20,-73.956535,40.746670,-73.930984,40.611687,2015-02-01 23:19:58
1383,2015-07-24 23:42:55,2015-07-25 00:03:14,6.35,-73.890167,40.746185,-73.942696,40.700733,2015-07-24 23:42:55
1457,2015-06-04 23:49:09,2015-06-05 00:03:56,3.30,-73.964035,40.803093,-73.950844,40.770973,2015-06-04 23:49:09
1532,2015-04-23 23:45:00,2015-04-24 00:02:25,2.80,-73.951622,40.714203,-73.918961,40.706001,2015-04-23 23:45:00
1603,2015-01-14 23:50:53,2015-01-15 00:01:32,3.60,-73.933624,40.751850,-73.949219,40.781185,2015-01-14 23:50:53
1914,2015-04-02 23:25:40,2015-04-03 00:02:19,5.19,-73.963890,40.808228,-73.987823,40.738365,2015-04-02 23:25:40
1962,2015-02-06 23:49:27,2015-02-07 00:14:04,4.40,-73.961739,40.713734,-73.933716,40.668762,2015-02-06 23:49:27
1997,2015-03-13 23:04:46,2015-03-14 00:00:37,15.10,-73.952721,40.804905,-73.963425,40.681480,2015-03-13 23:04:46
2054,2015-09-20 23:55:43,2015-09-21 00:24:30,10.23,-73.850014,40.753437,-73.977974,40.721340,2015-09-20 23:55:43
2306,2015-12-03 23:38:20,2015-12-04 00:06:49,4.51,-73.962410,40.712772,-73.972458,40.744850,2015-12-03 23:38:20
2308,2015-05-09 23:58:31,2015-05-10 00:10:33,2.70,-73.957932,40.670925,-73.991760,40.673538,2015-05-09 23:58:31
2313,2015-09-03 23:52:59,2015-09-04 00:03:10,3.88,-73.984550,40.687042,-74.014763,40.708015,2015-09-03 23:52:59
2409,2015-08-15 23:50:27,2015-08-16 00:03:15,2.00,-73.967194,40.683517,-73.948181,40.667049,2015-08-15 23:50:27
2626,2015-10-25 23:54:36,2015-10-26 00:14:47,3.27,-73.987450,40.692177,-73.939972,40.683723,2015-10-25 23:54:36
2926,2015-02-21 23:50:39,2015-02-22 00:03:37,3.36,-73.890862,40.746395,-73.866341,40.765671,2015-02-21 23:50:39
...,...,...,...,...,...,...,...,...
1996687,2015-03-06 23:53:37,2015-03-07 00:04:30,2.48,-73.977455,40.671848,-73.936470,40.671661,2015-03-06 23:53:37
1996697,2015-12-26 23:40:24,2015-12-27 00:01:43,7.40,-73.961800,40.682487,-74.028259,40.637611,2015-12-26 23:40:24
1996958,2015-02-27 23:52:11,2015-02-28 00:16:15,7.05,-73.943672,40.810291,-73.998131,40.756786,2015-02-27 23:52:11
1997114,2015-07-16 23:46:48,2015-07-17 00:10:57,9.10,-73.927414,40.679279,-73.795174,40.679176,2015-07-16 23:46:48
1997135,2015-07-04 23:53:10,2015-07-05 00:02:20,1.19,-73.927345,40.818298,-73.910500,40.819363,2015-07-04 23:53:10
1997167,2015-05-16 23:55:52,2015-05-17 00:14:35,1.95,-73.962219,40.716103,-73.939072,40.707687,2015-05-16 23:55:52
1997547,2015-12-24 23:54:28,2015-12-25 00:03:17,1.70,-73.952698,40.685196,-73.936493,40.695343,2015-12-24 23:54:28
1998051,2015-07-23 23:40:42,2015-07-24 00:08:03,4.00,-73.958527,40.721283,-74.001915,40.730286,2015-07-23 23:40:42
1998144,2015-05-05 23:53:28,2015-05-06 00:08:44,3.68,-73.977089,40.683178,-73.970253,40.638962,2015-05-05 23:53:28
1998221,2015-11-24 23:57:46,2015-11-25 00:09:35,2.42,-73.955910,40.676865,-73.989136,40.665657,2015-11-24 23:57:46
1998325,2015-03-18 23:48:36,2015-03-19 00:03:45,2.46,-73.951363,40.711975,-73.950272,40.693073,2015-03-18 23:48:36
1998479,2015-12-11 23:58:58,2015-12-12 00:18:09,5.70,-73.951927,40.725548,-73.974327,40.674026,2015-12-11 23:58:58
1998491,2015-08-24 23:31:49,2015-08-25 00:04:34,13.00,-73.925636,40.828018,-74.006050,40.722225,2015-08-24 23:31:49
1998519,2015-11-03 23:48:07,2015-11-04 00:04:31,3.98,-73.939003,40.821869,-73.975105,40.787594,2015-11-03 23:48:07
1998558,2015-04-23 23:57:27,2015-04-24 00:01:09,0.67,-73.911362,40.699753,-73.921326,40.705647,2015-04-23 23:57:27
1998600,2015-12-18 23:58:54,2015-12-19 00:05:59,1.28,-73.957016,40.716587,-73.938042,40.714561,2015-12-18 23:58:54
1998649,2015-07-30 23:48:45,2015-07-31 00:00:32,4.42,-73.829857,40.713711,-73.833427,40.672947,2015-07-30 23:48:45
1998739,2015-09-26 23:56:16,2015-09-27 00:05:39,1.40,-73.981804,40.679432,-73.986275,40.692612,2015-09-26 23:56:16
1998752,2015-04-27 23:29:16,2015-04-28 00:05:00,9.10,-73.874611,40.735058,-73.792351,40.771561,2015-04-27 23:29:16
1998755,2015-05-15 23:43:07,2015-05-16 00:09:29,5.55,-73.958473,40.713146,-73.983109,40.737942,2015-05-15 23:43:07
1999183,2015-03-11 23:46:45,2015-03-12 00:07:16,4.63,-73.956627,40.717072,-73.998436,40.740559,2015-03-11 23:46:45
1999198,2015-12-03 23:37:55,2015-12-04 00:00:34,9.10,-73.938873,40.821690,-73.845917,40.906193,2015-12-03 23:37:55
1999288,2015-10-01 23:55:33,2015-10-02 00:05:44,2.23,-73.955299,40.804565,-73.977341,40.784439,2015-10-01 23:55:33
1999340,2015-10-09 23:43:01,2015-10-10 00:18:28,6.98,-73.986839,40.702404,-73.984657,40.769356,2015-10-09 23:43:01
1999346,2015-05-16 23:55:39,2015-05-17 00:09:53,3.14,-73.906151,40.817604,-73.945099,40.790085,2015-05-16 23:55:39
1999434,2015-11-12 23:54:12,2015-11-13 00:12:56,8.31,-73.917801,40.769997,-73.953590,40.690407,2015-11-12 23:54:12
1999513,2015-09-14 23:45:33,2015-09-15 00:00:37,3.00,-73.953262,40.680618,-73.990013,40.661995,2015-09-14 23:45:33
1999524,2015-07-03 23:50:38,2015-07-04 00:07:10,3.99,-73.964226,40.710667,-73.996338,40.737911,2015-07-03 23:50:38
1999787,2015-11-28 23:57:32,2015-11-29 00:11:40,2.47,-73.961113,40.718941,-73.962135,40.690163,2015-11-28 23:57:32
1999880,2015-11-17 23:55:27,2015-11-18 00:11:25,8.97,-73.968491,40.639393,-73.958191,40.717342,2015-11-17 23:55:27

In [133]:
df['dropoff_datetime_new'] = df['dropoff_datetime']
mask2 = (pd.DatetimeIndex(df['pickup_datetime_new']).hour == 23) & (pd.DatetimeIndex(df['dropoff_datetime_new']).hour == 0)
df.loc[mask2, 'pickup_datetime_new'] = df.loc[mask2, 'pickup_datetime_new'] - pd.Timedelta(hours=23) + pd.Timedelta(days=1)
df.loc[mask2, 'dropoff_datetime_new'] = df.loc[mask2, 'dropoff_datetime_new'] + pd.Timedelta(hours=1)

In [134]:
df[(df.dropoff_datetime_new - df.pickup_datetime_new) == pd.Timedelta(0)]

,pickup_datetime,dropoff_datetime,trip_distance,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,pickup_datetime_new,dropoff_datetime_new
554,2015-06-07 00:19:35,2015-06-07 00:19:35,21.80,-73.703056,40.724209,-73.951302,40.768444,2015-06-07 00:19:35,2015-06-07 00:19:35
4920,2015-09-21 13:00:29,2015-09-21 13:00:29,61.15,-73.955727,40.805393,-73.876907,40.826256,2015-09-21 13:00:29,2015-09-21 13:00:29
13424,2015-12-04 22:41:52,2015-12-04 22:41:52,0.00,-73.896782,40.746185,-73.894981,40.746361,2015-12-04 22:41:52,2015-12-04 22:41:52
34671,2015-03-10 03:27:57,2015-03-10 03:27:57,0.00,-73.854233,40.927563,-73.854240,40.927555,2015-03-10 03:27:57,2015-03-10 03:27:57
35870,2015-10-02 00:00:00,2015-10-02 00:00:00,3.30,-73.891205,40.746830,-73.871162,40.774105,2015-10-02 00:00:00,2015-10-02 00:00:00
38539,2015-10-01 00:00:00,2015-10-01 00:00:00,4.27,-73.884438,40.851658,-73.926735,40.816113,2015-10-01 00:00:00,2015-10-01 00:00:00
43712,2015-06-06 23:28:03,2015-06-06 23:28:03,0.00,-73.885605,40.747353,-73.937531,40.758446,2015-06-06 23:28:03,2015-06-06 23:28:03
46282,2015-04-27 10:30:16,2015-04-27 10:30:16,0.00,-74.004028,40.654575,-73.991287,40.693462,2015-04-27 10:30:16,2015-04-27 10:30:16
54998,2015-12-02 00:36:35,2015-12-02 00:36:35,19.44,-73.971558,40.636246,-73.824364,40.776344,2015-12-02 00:36:35,2015-12-02 00:36:35
55326,2015-05-30 03:11:08,2015-05-30 03:11:08,0.00,-73.981430,40.689716,-73.981400,40.689713,2015-05-30 03:11:08,2015-05-30 03:11:08
58144,2015-11-08 07:34:04,2015-11-08 07:34:04,0.00,-73.879929,40.879826,-73.879921,40.879833,2015-11-08 07:34:04,2015-11-08 07:34:04
64308,2015-08-29 00:00:00,2015-08-29 00:00:00,3.08,-73.905289,40.655926,-73.957954,40.670815,2015-08-29 00:00:00,2015-08-29 00:00:00
103300,2014-10-10 12:34:00,2014-10-10 12:34:00,0.00,-73.947263,40.780005,-73.947193,40.780013,2014-10-10 12:34:00,2014-10-10 12:34:00
104175,2014-07-27 16:01:00,2014-07-27 16:01:00,0.00,-73.970427,40.750792,-73.970375,40.750843,2014-07-27 16:01:00,2014-07-27 16:01:00
105535,2014-05-08 01:35:00,2014-05-08 01:35:00,0.00,-74.039340,40.736980,-74.039300,40.737040,2014-05-08 01:35:00,2014-05-08 01:35:00
107870,2014-04-02 13:09:00,2014-04-02 13:09:00,0.06,-73.979687,40.738997,-73.999195,40.734907,2014-04-02 13:09:00,2014-04-02 13:09:00
110622,2014-12-04 07:38:00,2014-12-04 07:38:00,0.00,-73.948527,40.788295,-73.952368,40.810812,2014-12-04 07:38:00,2014-12-04 07:38:00
124323,2014-05-29 18:07:00,2014-05-29 18:07:00,0.00,-74.008190,40.714715,-74.005958,40.739912,2014-05-29 18:07:00,2014-05-29 18:07:00
140372,2014-01-10 18:43:00,2014-01-10 18:43:00,0.00,-73.992632,40.755130,-73.954827,40.773982,2014-01-10 18:43:00,2014-01-10 18:43:00
146250,2014-06-16 22:21:00,2014-06-16 22:21:00,0.00,-73.965307,40.694792,-73.965318,40.694787,2014-06-16 22:21:00,2014-06-16 22:21:00
200663,2015-06-27 06:21:32,2015-06-27 06:21:32,0.00,-73.819130,40.751434,-73.819092,40.751411,2015-06-27 06:21:32,2015-06-27 06:21:32
223946,2014-04-05 18:20:00,2014-04-05 18:20:00,0.03,-73.789320,40.646770,-73.794680,40.644810,2014-04-05 18:20:00,2014-04-05 18:20:00
223952,2014-03-05 10:36:00,2014-03-05 10:36:00,0.00,-74.007780,40.705345,-74.007825,40.705272,2014-03-05 10:36:00,2014-03-05 10:36:00
223953,2014-03-03 08:15:00,2014-03-03 08:15:00,0.01,-73.990067,40.756500,-73.990108,40.756700,2014-03-03 08:15:00,2014-03-03 08:15:00
223956,2014-03-19 08:18:00,2014-03-19 08:18:00,0.01,-73.912665,40.769842,-73.912718,40.769850,2014-03-19 08:18:00,2014-03-19 08:18:00
223957,2014-09-14 16:55:00,2014-09-14 16:55:00,0.12,-73.789145,40.641787,-73.786727,40.641657,2014-09-14 16:55:00,2014-09-14 16:55:00
223965,2014-01-11 15:48:00,2014-01-11 15:48:00,0.02,-73.961812,40.718582,-73.961717,40.718532,2014-01-11 15:48:00,2014-01-11 15:48:00
223970,2014-03-28 07:17:00,2014-03-28 07:17:00,0.07,-73.985975,40.722637,-73.885507,40.773152,2014-03-28 07:17:00,2014-03-28 07:17:00
223972,2014-05-09 11:21:00,2014-05-09 11:21:00,0.07,-73.964262,40.756927,-73.963965,40.757605,2014-05-09 11:21:00,2014-05-09 11:21:00
223978,2014-12-30 12:04:00,2014-12-30 12:04:00,0.00,-73.969832,40.787325,-73.969817,40.787327,2014-12-30 12:04:00,2014-12-30 12:04:00
...,...,...,...,...,...,...,...,...,...
1293979,2015-03-25 20:52:46,2015-03-25 20:52:46,0.00,-73.937553,40.758278,-73.937576,40.758251,2015-03-25 20:52:46,2015-03-25 20:52:46
1300496,2014-05-31 00:29:37,2014-05-31 00:29:37,0.04,-73.925652,40.828152,-73.924583,40.830051,2014-05-31 00:29:37,2014-05-31 00:29:37
1308057,2014-06-24 07:59:36,2014-06-24 07:59:36,0.00,-73.861725,40.768372,-73.862350,40.768784,2014-06-24 07:59:36,2014-06-24 07:59:36
1308931,2014-03-06 16:36:00,2014-03-06 16:36:00,0.00,-73.982262,40.775902,-73.982346,40.775917,2014-03-06 16:36:00,2014-03-06 16:36:00
1333686,2015-02-25 18:00:21,2015-02-25 18:00:21,0.14,-73.941124,40.788162,-73.934845,40.804935,2015-02-25 18:00:21,2015-02-25 18:00:21
1344532,2015-04-05 00:01:37,2015-04-05 00:01:37,3.95,-73.921288,40.867813,-73.890900,40.746368,2015-04-05 00:01:37,2015-04-05 00:01:37
1350525,2014-11-13 00:00:00,2014-11-13 00:00:00,1.12,-73.939949,40.840446,-73.939522,40.853481,2014-11-13 00:00:00,2014-11-13 00:00:00
1375183,2014-08-15 21:29:08,2014-08-15 21:29:08,3.62,-73.920128,40.815907,-73.918823,40.815594,2014-08-15 21:29:08,2014-08-15 21:29:08
1396550,2014-10-02 21:27:41,2014-10-02 21:27:41,0.00,-73.878525,40.880661,-73.878616,40.880638,2014-10-02 21:27:41,2014-10-02 21:27:41
1413349,2014-06-21 23:27:26,2014-06-21 23:27:26,0.00,-73.890816,40.746933,-73.890129,40.747059,2014-06-21 23:27:26,2014-06-21 23:27:26
1425100,2014-11-02 00:23:52,2014-11-02 00:23:52,13.75,-73.939865,40.798046,-73.800903,40.708344,2014-11-02 00:23:52,2014-11-02 00:23:52
1432808,2014-01-06 19:34:00,2014-01-06 19:34:00,0.05,-73.954407,40.775581,-73.953552,40.775208,2014-01-06 19:34:00,2014-01-06 19:34:00
1475732,2014-12-15 21:27:36,2014-12-15 21:27:36,0.00,-73.940369,40.685658,-73.940399,40.685688,2014-12-15 21:27:36,2014-12-15 21:27:36
1547403,2014-12-05 09:42:36,2014-12-05 09:42:36,0.00,-73.826080,40.865063,-73.826103,40.865067,2014-12-05 09:42:36,2014-12-05 09:42:36
1584638,2014-12-12 15:47:21,2014-12-12 15:47:21,6.62,-73.976051,40.686974,-74.001038,40.636017,2014-12-12 15:47:21,2014-12-12 15:47:21
1595965,2014-12-05 00:08:44,2014-12-05 00:08:44,7.65,-73.951797,40.812080,-73.965408,40.760319,2014-12-05 00:08:44,2014-12-05 00:08:44
1619746,2014-09-07 00:31:43,2014-09-07 00:31:43,2.45,-73.944077,40.719852,-73.946449,40.722256,2014-09-07 00:31:43,2014-09-07 00:31:43
1668017,2015-11-01 01:46:21,2015-11-01 01:46:21,11.60,-73.988556,40.727421,-73.924461,40.864120,2015-11-01 01:46:21,2015-11-01 01:46:21
1701216,2015-05-13 00:08:23,2015-05-13 00:08:23,1.71,-73.979851,40.764866,-73.974716,40.779446,2015-05-13 00:08:23,2015-05-13 00:08:23
1702675,2015-12-17 00:00:00,2015-12-17 00:00:00,5.16,-73.982773,40.739243,-73.971542,40.795483,2015-12-17 00:00:00,2015-12-17 00:00:00
1731793,2015-10-06 00:00:00,2015-10-06 00:00:00,3.52,-73.981888,40.778210,-73.993240,40.738770,2015-10-06 00:00:00,2015-10-06 00:00:00
1889308,2015-10-13 11:20:31,2015-10-13 11:20:31,0.00,-73.977852,40.748863,-73.776733,40.645660,2015-10-13 11:20:31,2015-10-13 11:20:31
1894844,2015-08-28 00:13:12,2015-08-28 00:13:12,17.46,-73.790993,40.645401,-73.986847,40.732578,2015-08-28 00:13:12,2015-08-28 00:13:12
1904747,2015-02-26 22:10:14,2015-02-26 22:10:14,0.00,-73.932693,40.848938,-73.932716,40.848927,2015-02-26 22:10:14,2015-02-26 22:10:14
1904945,2015-03-19 08:13:03,2015-03-19 08:13:03,0.03,-73.939171,40.750565,-73.940491,40.751095,2015-03-19 08:13:03,2015-03-19 08:13:03
1910410,2015-06-20 00:05:52,2015-06-20 00:05:52,11.32,-73.844200,40.721497,-73.978844,40.782574,2015-06-20 00:05:52,2015-06-20 00:05:52
1914241,2015-09-22 07:54:49,2015-09-22 07:54:49,0.02,-73.886986,40.827927,-73.887474,40.828293,2015-09-22 07:54:49,2015-09-22 07:54:49
1922151,2015-03-09 00:02:36,2015-03-09 00:02:36,0.02,-73.915604,40.655602,-73.915344,40.655758,2015-03-09 00:02:36,2015-03-09 00:02:36
1956773,2015-06-07 00:00:00,2015-06-07 00:00:00,1.10,-73.909546,40.857681,-73.920975,40.846714,2015-06-07 00:00:00,2015-06-07 00:00:00
1959108,2015-05-28 00:02:45,2015-05-28 00:02:45,2.47,-73.922173,40.836037,-73.939026,40.842831,2015-05-28 00:02:45,2015-05-28 00:02:45

In [136]:
df = df[(df.dropoff_datetime_new - df.pickup_datetime) != pd.Timedelta(0)]

In [137]:
df['travel_time'] = df.dropoff_datetime_new - df.pickup_datetime_new
df.loc[:, 'travel_time'] = df['travel_time'].dt.total_seconds() / 60

C:\Users\Stevens\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\Stevens\Anaconda3\lib\site-packages\pandas\core\indexing.py:517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [138]:
df1 = df[['pickup_datetime_new', 'dropoff_datetime_new', 'travel_time', 'trip_distance', 'pickup_longitude', 'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude']].copy()

In [147]:
df1[(pd.DatetimeIndex(df1['pickup_datetime_new']).hour < 22) & (pd.DatetimeIndex(df1['dropoff_datetime_new']).hour == 0) & (pd.DatetimeIndex(df1['dropoff_datetime_new']).minute == 0) & (pd.DatetimeIndex(df1['dropoff_datetime_new']).second == 0)].sort_values(by='trip_distance', ascending=False)

,pickup_datetime_new,dropoff_datetime_new,travel_time,trip_distance,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude
392534,2014-04-18 17:09:53,2014-04-19,410.116667,21.72,-73.916702,40.848446,-73.979660,40.793026
1145258,2015-08-23 05:30:44,2015-08-24,1109.266667,20.14,-73.781960,40.644669,-73.953331,40.788410
1758522,2015-07-14 18:31:21,2015-07-15,328.650000,19.50,-73.788261,40.641495,-73.951439,40.825039
991596,2015-09-14 14:27:50,2015-09-15,572.166667,19.16,-73.950851,40.826599,-73.789848,40.646927
1104486,2015-02-09 14:55:11,2015-02-10,544.816667,19.09,-73.776855,40.645851,-73.979691,40.726082
781212,2015-09-20 12:52:13,2015-09-21,667.783333,19.01,-73.781990,40.644592,-73.942574,40.786335
1495453,2014-12-02 18:45:08,2014-12-03,314.866667,18.92,-73.965645,40.805504,-73.790001,40.646919
1724863,2015-08-30 18:17:41,2015-08-31,342.316667,18.84,-73.782082,40.644642,-73.980042,40.766350
1010271,2015-09-19 17:53:47,2015-09-20,366.216667,18.13,-73.918701,40.764774,-73.960968,40.594177
1661670,2015-08-06 20:47:58,2015-08-07,192.033333,18.10,-73.782608,40.646961,-73.953011,40.779499
713978,2015-10-09 08:38:28,2015-10-10,921.533333,18.06,-73.789062,40.641560,-73.984642,40.761581
1793703,2015-07-19 07:23:00,2015-07-20,997.000000,17.81,-73.794151,40.657318,-73.992943,40.756210
1888118,2015-04-22 16:57:15,2015-04-23,422.750000,17.80,-73.781952,40.644749,-73.918053,40.731709
1806106,2015-01-30 16:12:24,2015-01-31,467.600000,17.56,-73.789604,40.646873,-73.986481,40.730438
1947746,2015-10-29 20:18:34,2015-10-30,221.433333,16.66,-73.789452,40.642750,-73.952614,40.711273
1819932,2015-08-16 07:03:01,2015-08-17,1016.983333,16.49,-73.783310,40.648617,-73.962524,40.759834
663114,2015-10-05 17:21:49,2015-10-06,398.183333,15.24,-73.913452,40.756378,-73.897369,40.813541
1165407,2014-11-24 13:23:20,2014-11-25,636.666667,13.53,-73.873779,40.774101,-73.802048,40.663761
1892014,2015-04-14 21:19:30,2015-04-15,160.500000,13.51,-73.782127,40.644730,-73.919769,40.615742
1900073,2015-10-23 17:01:37,2015-10-24,418.383333,13.30,-73.826126,40.746616,-73.994308,40.720421
259958,2015-09-16 08:37:25,2015-09-17,922.583333,13.25,-74.027565,40.624218,-73.969360,40.760998
1729706,2015-04-18 11:39:18,2015-04-19,740.700000,13.13,-73.872887,40.774090,-73.993477,40.669312
1004354,2015-11-01 07:57:29,2015-11-02,962.516667,12.98,-73.918503,40.825699,-73.820900,40.714634
1824363,2015-04-13 10:45:01,2015-04-14,794.983333,12.95,-73.877434,40.772251,-74.034760,40.726505
1405206,2014-05-20 12:58:56,2014-05-21,661.066667,12.79,-73.958153,40.668877,-73.788879,40.641674
1808649,2015-05-26 13:12:10,2015-05-27,647.833333,12.78,-73.776718,40.645363,-73.842758,40.575603
1186289,2015-01-18 16:57:18,2015-01-19,422.700000,12.51,-73.777031,40.644958,-73.971230,40.680580
269922,2015-12-12 03:15:20,2015-12-13,1244.666667,12.50,-73.912674,40.759930,-73.777840,40.741207
700089,2015-12-01 09:46:21,2015-12-02,853.650000,12.46,-73.874634,40.774139,-74.002792,40.760609
1904672,2015-06-12 13:11:30,2015-06-13,648.500000,12.36,-73.976753,40.668835,-73.862068,40.768597
...,...,...,...,...,...,...,...,...
987988,2015-03-03 11:12:16,2015-03-04,767.733333,0.10,-73.973114,40.638554,-73.974274,40.644672
975636,2015-09-05 15:43:37,2015-09-06,496.383333,0.09,-73.849045,40.884655,-73.852348,40.879761
273146,2015-11-25 00:24:10,2015-11-26,1415.833333,0.09,-73.890060,40.746971,-73.887283,40.747341
1231492,2015-12-02 19:32:42,2015-12-03,267.300000,0.06,-73.939903,40.801277,-73.938828,40.800812
1586147,2014-05-24 01:45:42,2014-05-25,1334.300000,0.05,-73.890587,40.746456,-73.889732,40.745895
266587,2015-11-02 07:53:44,2015-11-03,966.266667,0.04,-73.926964,40.830944,-73.927635,40.830151
205676,2015-10-14 10:59:57,2015-10-15,780.050000,0.04,-73.902931,40.861687,-73.902458,40.862411
992707,2015-09-27 06:08:02,2015-09-28,1071.966667,0.02,-73.909576,40.822533,-73.911148,40.822212
366206,2014-08-12 01:24:40,2014-08-13,1355.333333,0.01,-73.895782,40.768272,-73.895660,40.768269
1973117,2015-10-01 15:08:35,2015-10-02,531.416667,0.01,-73.908546,40.834362,-73.908707,40.834049
1203424,2015-10-30 19:38:47,2015-10-31,261.216667,0.00,-73.948891,40.695446,-73.950989,40.695217
8784,2015-10-22 10:37:42,2015-10-23,802.300000,0.00,-73.936951,40.764809,-73.937012,40.764679
6925,2015-11-20 13:48:24,2015-11-21,611.600000,0.00,-73.936852,40.764793,-73.936920,40.764671
1000613,2014-04-01 07:42:52,2014-04-02,977.133333,0.00,-73.891434,40.870075,-73.902596,40.831177
1644697,2014-05-28 02:07:15,2014-05-29,1312.750000,0.00,-73.828232,40.837170,-73.828178,40.837223
1287522,2015-04-17 21:28:34,2015-04-18,151.433333,0.00,-73.809883,40.667091,-73.809578,40.667221
1289377,2015-12-30 20:51:35,2015-12-31,188.416667,0.00,-73.937393,40.764755,-73.936821,40.764923
1592923,2014-05-09 07:35:41,2014-05-10,984.316667,0.00,-73.781723,40.644482,-73.781761,40.644524
1462203,2014-07-29 01:30:41,2014-07-30,1349.316667,0.00,-73.916374,40.846916,-73.916328,40.846893
1458386,2014-02-14 10:20:27,2014-02-15,819.550000,0.00,-73.937828,40.758404,-73.937691,40.758350
1950626,2015-06-19 21:34:26,2015-06-20,145.566667,0.00,-73.873230,40.672638,-73.873947,40.673519
1010616,2015-11-22 17:52:04,2015-11-23,367.933333,0.00,-73.936806,40.764679,-73.937088,40.764576
1247678,2015-05-04 20:33:48,2015-05-05,206.200000,0.00,-73.950554,40.786621,-73.956635,40.802544
1259877,2015-12-02 20:01:01,2015-12-03,238.983333,0.00,-73.980080,40.687809,-73.949371,40.724648
1918449,2015-09-25 16:18:51,2015-09-26,461.150000,0.00,-73.913528,40.756161,-73.917397,40.764984
1255305,2015-12-09 09:13:54,2015-12-10,886.100000,0.00,-73.782196,40.644085,-73.782204,40.644169
1510582,2014-12-28 21:42:01,2014-12-29,137.983333,0.00,-73.937607,40.797054,-73.937744,40.797035
1529053,2014-08-31 21:34:24,2014-09-01,145.600000,0.00,-73.919151,40.849884,-73.919174,40.849949
1399293,2014-02-20 15:53:21,2014-02-21,486.650000,0.00,-73.937424,40.758060,-73.935074,40.634266
1479337,2014-11-04 19:13:41,2014-11-05,286.316667,0.00,-73.921555,40.821140,-73.921486,40.821060

In [148]:
mask3 = (pd.DatetimeIndex(df1['pickup_datetime_new']).hour < 22) & (pd.DatetimeIndex(df1['dropoff_datetime_new']).hour == 0) & (pd.DatetimeIndex(df1['dropoff_datetime_new']).minute == 0) & (pd.DatetimeIndex(df1['dropoff_datetime_new']).second == 0)
df1 = df1[~mask3]

In [154]:
df1[(pd.DatetimeIndex(df1['pickup_datetime_new']).day != pd.DatetimeIndex(df1['dropoff_datetime_new']).day) & (pd.DatetimeIndex(df1['pickup_datetime_new']).hour !=23) & (pd.DatetimeIndex(df1['dropoff_datetime_new']).hour !=0)]

,pickup_datetime_new,dropoff_datetime_new,travel_time,trip_distance,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude
157,2015-12-02 21:58:44,2015-12-03 21:11:18,1392.566667,5.10,-73.987030,40.692997,-73.945175,40.631821
661,2015-10-05 09:41:17,2015-10-06 08:57:44,1396.450000,3.36,-73.977356,40.693470,-74.009109,40.702419
725,2015-10-03 17:32:43,2015-10-04 17:29:04,1436.350000,0.82,-73.952454,40.726677,-73.956322,40.717117
1053,2015-01-31 22:00:42,2015-02-01 21:54:02,1433.333333,5.38,-73.950012,40.792774,-73.917732,40.837845
1557,2015-04-20 20:39:54,2015-04-21 18:51:42,1331.800000,2.64,-73.923965,40.743996,-73.930641,40.771160
2044,2015-12-10 15:17:34,2015-12-11 15:11:29,1433.916667,1.88,-73.966270,40.804192,-73.945808,40.825397
2126,2015-05-09 15:29:57,2015-05-10 14:46:12,1396.250000,2.91,-73.937592,40.804203,-73.961304,40.768734
2247,2015-11-15 17:53:17,2015-11-16 17:51:33,1438.266667,2.40,-73.993019,40.702629,-73.980438,40.681084
2460,2015-11-20 18:10:53,2015-11-21 17:28:07,1397.233333,5.90,-73.978973,40.683357,-73.909500,40.665112
2650,2015-12-19 17:23:39,2015-12-20 17:15:16,1431.616667,0.96,-73.873375,40.750877,-73.884430,40.749889
3416,2015-10-02 17:18:03,2015-10-03 17:08:47,1430.733333,1.20,-73.920570,40.756981,-73.906975,40.772099
4441,2015-11-09 18:04:35,2015-11-10 17:57:04,1432.483333,1.79,-73.943787,40.807152,-73.937943,40.792732
6303,2015-10-20 19:46:09,2015-10-21 18:51:27,1385.300000,0.87,-73.948784,40.813454,-73.940109,40.820137
6414,2015-10-05 02:14:00,2015-10-06 01:55:30,1421.500000,2.78,-73.903526,40.745457,-73.859673,40.741627
6636,2015-12-24 16:39:32,2015-12-25 16:35:18,1435.766667,5.00,-73.953735,40.728802,-73.997368,40.729923
6762,2015-12-06 01:55:30,2015-12-07 01:47:54,1432.400000,5.95,-73.946548,40.826763,-73.994347,40.761166
7038,2015-10-09 18:14:47,2015-10-10 16:29:29,1334.700000,2.08,-73.844482,40.721500,-73.853447,40.740467
7129,2015-09-11 19:12:44,2015-09-12 18:54:22,1421.633333,1.66,-73.990860,40.699772,-73.976105,40.684082
8127,2015-12-11 20:21:45,2015-12-12 19:57:55,1416.166667,9.89,-73.807610,40.700577,-73.919769,40.764675
8822,2015-10-21 15:16:01,2015-10-22 15:14:55,1438.900000,5.83,-73.937355,40.804405,-73.988625,40.769154
9031,2015-12-23 20:09:03,2015-12-24 20:03:46,1434.716667,0.92,-73.950462,40.723129,-73.960426,40.715302
9451,2015-12-13 20:53:19,2015-12-14 20:42:41,1429.366667,4.08,-73.919670,40.743519,-73.958130,40.715385
9708,2015-12-09 22:54:16,2015-12-10 21:54:25,1380.150000,3.45,-73.976425,40.687141,-73.933884,40.666241
9710,2015-03-04 21:23:29,2015-03-05 21:22:03,1438.566667,2.21,-73.935211,40.796112,-73.943817,40.820171
11101,2015-12-07 19:34:57,2015-12-08 19:33:14,1438.283333,1.92,-73.924690,40.739746,-73.916306,40.762314
12219,2015-12-28 11:20:50,2015-12-29 09:55:31,1354.683333,0.47,-73.912689,40.766647,-73.906990,40.770958
12538,2015-08-30 09:07:31,2015-08-31 08:17:29,1389.966667,1.69,-73.890877,40.832218,-73.912727,40.831081
13541,2015-06-14 03:40:54,2015-06-15 03:15:27,1414.550000,0.01,-73.919487,40.700356,-73.919411,40.700668
13694,2015-10-08 16:04:45,2015-10-09 16:01:40,1436.916667,0.68,-73.951416,40.799534,-73.948685,40.807438
13856,2015-05-16 17:38:38,2015-05-17 16:46:38,1388.000000,1.22,-73.943016,40.826801,-73.937256,40.815006
...,...,...,...,...,...,...,...,...
1985162,2015-11-05 16:49:47,2015-11-06 16:46:24,1436.616667,3.53,-73.953934,40.742641,-73.929642,40.707439
1985327,2015-08-21 19:58:40,2015-08-22 19:53:15,1434.583333,1.35,-73.950424,40.684422,-73.940376,40.689693
1985571,2015-10-11 01:49:49,2015-10-12 01:43:34,1433.750000,0.14,-73.942703,40.720303,-73.944160,40.720509
1985834,2015-11-06 12:21:47,2015-11-07 11:48:31,1406.733333,4.54,-73.829918,40.713776,-73.812431,40.664253
1986861,2015-11-10 11:44:00,2015-11-11 11:22:12,1418.200000,18.70,-73.946823,40.711456,-73.776306,40.645840
1987638,2015-11-12 14:27:50,2015-11-13 13:51:42,1403.866667,11.61,-73.921982,40.795925,-73.797112,40.723907
1988451,2015-12-29 14:47:37,2015-12-30 14:22:51,1415.233333,2.92,-73.953400,40.810150,-73.978195,40.773163
1988471,2015-04-04 11:53:10,2015-04-05 10:57:08,1383.966667,0.71,-73.916763,40.846638,-73.920090,40.838612
1988744,2015-11-03 11:48:37,2015-11-04 11:46:41,1438.066667,3.13,-73.940681,40.798264,-73.953949,40.774708
1989528,2015-07-22 02:42:57,2015-07-23 01:49:36,1386.650000,1.62,-73.925499,40.827862,-73.937653,40.840118
1990031,2015-09-12 21:45:53,2015-09-13 21:36:43,1430.833333,2.62,-73.870293,40.762016,-73.911629,40.769009
1990480,2015-10-30 13:49:11,2015-10-31 13:32:00,1422.816667,1.32,-73.985229,40.662552,-73.988235,40.674835
1990848,2015-12-09 11:12:00,2015-12-10 10:20:45,1388.750000,3.40,-73.922600,40.760727,-73.961967,40.766895
1991295,2015-10-26 14:29:03,2015-10-27 13:27:56,1378.883333,0.88,-73.947495,40.815708,-73.951080,40.806793
1991563,2015-01-10 20:40:35,2015-01-11 20:23:34,1422.983333,1.87,-73.978752,40.683971,-73.999748,40.673122
1991889,2015-10-18 21:57:19,2015-10-19 21:45:02,1427.716667,2.14,-73.829994,40.713741,-73.806511,40.690922
1993030,2015-03-22 02:19:54,2015-03-23 02:12:41,1432.783333,0.85,-73.929024,40.819088,-73.942924,40.823162
1993053,2015-09-17 14:36:18,2015-09-18 13:47:32,1391.233333,1.66,-73.925652,40.761780,-73.914673,40.746212
1993269,2015-07-22 22:26:40,2015-07-23 21:29:44,1383.066667,0.64,-73.948715,40.803268,-73.951286,40.809834
1993470,2015-12-16 21:58:14,2015-12-17 21:17:50,1399.600000,1.12,-73.921272,40.766582,-73.906731,40.773304
1994341,2015-09-17 09:59:22,2015-09-18 09:57:30,1438.133333,0.75,-73.989204,40.692944,-73.977997,40.696011
1994542,2015-10-28 22:52:01,2015-10-29 22:48:27,1436.433333,0.56,-73.949753,40.680531,-73.947594,40.687157
1995170,2015-11-15 05:28:30,2015-11-16 05:13:26,1424.933333,1.09,-73.948288,40.803852,-73.936035,40.811855
1995273,2015-11-19 16:39:12,2015-11-20 16:12:31,1413.316667,1.63,-73.954498,40.789692,-73.957222,40.771713
1995432,2015-09-29 19:55:00,2015-09-30 19:53:48,1438.800000,0.00,-73.930977,40.656811,-73.930984,40.656826
1996468,2015-12-31 01:44:42,2016-01-01 01:32:55,1428.216667,0.32,-73.956314,40.681236,-73.959824,40.681103
1996826,2015-09-25 22:49:00,2015-09-26 22:38:09,1429.150000,3.89,-73.950264,40.719711,-73.902618,40.744625
1997238,2015-11-26 19:52:32,2015-11-27 19:28:14,1415.700000,1.95,-73.886436,40.747471,-73.918770,40.759010
1997609,2015-09-26 09:38:24,2015-09-27 09:12:09,1413.750000,5.68,-73.915855,40.839645,-73.838707,40.852612
1999372,2015-09-10 07:46:31,2015-09-11 07:42:55,1436.400000,1.53,-73.950890,40.665619,-73.956215,40.648651

In [155]:
#Swap pickup and drop off if the travel time is way too high
mask4 = (pd.DatetimeIndex(df1['pickup_datetime_new']).day != pd.DatetimeIndex(df1['dropoff_datetime_new']).day) & (pd.DatetimeIndex(df1['pickup_datetime_new']).hour !=23) & (pd.DatetimeIndex(df1['dropoff_datetime_new']).hour !=0)
df1.loc[df1[mask4].index, ['pickup_datetime_new', 'dropoff_datetime_new']] = df1.loc[df1[mask4].index, ['dropoff_datetime_new', 'pickup_datetime_new']].values
df1.loc[mask4, 'pickup_datetime_new'] = df1.loc[mask4, 'pickup_datetime_new'] - pd.Timedelta(days=1)
df1['travel_time'] = df1.dropoff_datetime_new - df1.pickup_datetime_new
df1.loc[:, 'travel_time'] = df1['travel_time'].dt.total_seconds() / 60

In [162]:
df1[(pd.DatetimeIndex(df1['pickup_datetime_new']).hour > pd.DatetimeIndex(df1['dropoff_datetime_new']).hour) & (pd.DatetimeIndex(df1['pickup_datetime_new']).hour < 3)].sort_values(by='trip_distance')

,pickup_datetime_new,dropoff_datetime_new,travel_time,trip_distance,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude
1457212,2014-06-25 01:54:55,2014-06-26 00:55:02,1380.116667,0.00,-73.881813,40.747868,-73.883690,40.747673
1463263,2014-07-16 01:15:10,2014-07-17 00:15:35,1380.416667,0.00,-73.937386,40.758396,-73.937378,40.758404
1436979,2014-05-20 01:29:14,2014-05-21 00:31:51,1382.616667,0.48,-73.940948,40.798286,-73.932999,40.795238
1986518,2015-11-18 01:03:14,2015-11-19 00:46:14,1423.000000,0.67,-73.952316,40.695053,-73.965752,40.693493
1728951,2015-01-10 01:10:12,2015-01-11 00:55:19,1425.116667,0.85,-73.994766,40.761288,-73.987167,40.760277
1524383,2014-04-26 01:05:54,2014-04-27 00:06:18,1380.400000,0.98,-73.957474,40.811901,-73.971321,40.693336
16403,2015-12-16 01:05:06,2015-12-17 00:02:12,1377.100000,0.99,-73.990562,40.686443,-74.001450,40.687656
1036374,2015-11-11 01:37:26,2015-11-12 00:52:07,1394.683333,0.99,-73.842735,40.839935,-73.857880,40.839771
1276567,2015-10-10 01:13:38,2015-10-11 00:07:24,1373.766667,1.05,-73.944908,40.717491,-73.959770,40.720043
1542650,2014-04-29 01:38:47,2014-04-30 00:42:27,1383.666667,1.07,-73.967529,40.696129,-74.004021,40.679382
1232540,2015-06-05 01:02:47,2015-06-06 00:08:20,1385.550000,1.15,-73.961151,40.680504,-73.973976,40.689754
298831,2015-04-04 01:19:08,2015-04-05 00:47:46,1408.633333,1.23,-73.980469,40.660446,-73.972992,40.646912
1948693,2015-11-14 01:58:07,2015-11-15 00:57:36,1379.483333,1.33,-73.988838,40.694088,-73.975456,40.687092
1111629,2015-12-20 01:09:44,2015-12-21 00:45:46,1416.033333,1.35,-73.997147,40.741982,-73.983833,40.743950
1378743,2014-06-22 01:02:00,2014-06-24 00:58:00,2876.000000,1.36,-73.870979,40.733250,-73.877335,40.719749
202594,2015-12-04 01:17:37,2015-12-05 00:56:27,1418.833333,1.54,-73.928635,40.866867,-73.931458,40.852516
1695234,2014-07-27 01:04:00,2014-07-28 00:10:58,1386.966667,1.55,-73.991188,40.689274,-73.967110,40.684097
86945,2015-10-15 01:35:54,2015-10-16 00:15:52,1359.966667,1.57,-73.844322,40.721478,-73.847771,40.734478
6243,2015-09-27 01:23:34,2015-09-28 00:47:33,1403.983333,1.74,-73.949913,40.681911,-73.925194,40.689919
663685,2015-09-20 01:15:14,2015-09-21 00:55:55,1420.683333,2.08,-73.963631,40.710403,-73.989143,40.720142
1203146,2015-03-27 01:13:43,2015-03-28 00:59:45,1426.033333,2.46,-73.957458,40.717831,-73.929787,40.705353
1491361,2014-07-12 01:05:22,2014-07-13 00:09:45,1384.383333,2.52,-73.976784,40.687199,-73.975548,40.687214
1922122,2015-04-11 01:02:49,2015-04-12 00:50:32,1427.716667,2.56,-73.947418,40.632565,-73.905556,40.635418
1498605,2014-11-01 01:24:39,2014-11-02 00:36:12,1391.550000,2.75,-73.988251,40.666553,-73.960632,40.653675
1521929,2014-02-09 01:07:58,2014-02-10 00:59:15,1431.283333,2.79,-73.957993,40.721718,-73.986092,40.722397
266186,2015-07-25 01:12:05,2015-07-26 00:54:56,1422.850000,2.82,-73.927765,40.763145,-73.935555,40.736748
1165782,2014-04-19 02:30:36,2014-04-20 00:30:49,1320.216667,2.97,-73.909431,40.775185,-73.883766,40.748093
1689392,2014-04-29 01:32:45,2014-04-30 00:44:18,1391.550000,3.02,-73.991623,40.670708,-73.948341,40.690872
289134,2015-10-10 01:15:39,2015-10-11 00:52:49,1417.166667,3.11,-73.937073,40.804226,-73.904831,40.833111
1392194,2014-06-15 01:24:33,2014-06-16 00:30:38,1386.083333,3.17,-73.935013,40.696896,-73.960747,40.672371
1531608,2014-06-07 01:25:49,2014-06-08 00:31:06,1385.283333,3.28,-73.949142,40.785229,-73.921555,40.820007
399962,2014-05-18 01:13:28,2014-05-19 00:21:09,1387.683333,3.58,-73.908691,40.691051,-73.947960,40.724731
81640,2015-12-16 01:13:31,2015-12-17 00:48:17,1414.766667,3.76,-73.844116,40.721111,-73.791588,40.713871
253375,2015-09-10 01:17:38,2015-09-11 00:28:49,1391.183333,5.15,-73.957794,40.717697,-73.946236,40.715591
996269,2015-11-26 01:01:18,2015-11-27 00:56:52,1435.566667,5.23,-73.916191,40.764462,-73.984184,40.748814
388025,2014-12-21 01:01:09,2014-12-22 00:33:40,1412.516667,5.40,-73.969398,40.689587,-73.980057,40.734821
1919476,2015-09-18 01:35:56,2015-09-19 00:49:14,1393.300000,8.03,-73.955299,40.722771,-73.984314,40.664124
1684718,2014-04-29 01:19:10,2014-04-30 00:55:39,1416.483333,9.37,-73.964752,40.682953,-73.883270,40.633640
1450061,2014-04-01 01:45:47,2014-04-02 00:14:38,1348.850000,9.62,-73.958038,40.721813,-73.955864,40.772366
427657,2014-05-30 01:17:00,2014-06-01 00:44:00,2847.000000,10.98,-73.843636,40.755981,-73.986115,40.718037
1418512,2014-04-20 01:33:33,2014-04-21 00:56:37,1403.066667,13.88,-73.945969,40.816216,-73.808777,40.691563
1893868,2015-09-17 01:11:03,2015-09-18 00:57:03,1426.000000,14.90,-73.988541,40.722767,-73.948524,40.778072
1510594,2014-07-21 01:02:13,2014-07-22 00:06:46,1384.550000,14.94,-73.830475,40.759392,-73.954208,40.639835

In [163]:
mask5 = (pd.DatetimeIndex(df1['pickup_datetime_new']).hour > pd.DatetimeIndex(df1['dropoff_datetime_new']).hour) & (pd.DatetimeIndex(df1['pickup_datetime_new']).hour < 3)
df1.loc[mask5, 'pickup_datetime_new'] = df1.loc[mask5, 'pickup_datetime_new'] + pd.Timedelta(days=1)
df1.loc[mask5, 'dropoff_datetime_new'] = df1.loc[mask5, 'dropoff_datetime_new'] + pd.Timedelta(hours=1)

In [166]:
df1[(pd.DatetimeIndex(df1['pickup_datetime_new']).hour > pd.DatetimeIndex(df1['dropoff_datetime_new']).hour) & (pd.DatetimeIndex(df1['dropoff_datetime_new']).hour > 21)].sort_values(by='trip_distance')

,pickup_datetime_new,dropoff_datetime_new,travel_time,trip_distance,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude
1263405,2015-03-22 23:26:22,2015-03-23 22:28:43,1382.350000,0.47,-73.939644,40.840832,-73.937943,40.847530
1252111,2015-11-23 23:26:25,2015-11-24 22:55:56,1409.516667,0.72,-73.879501,40.873615,-73.889694,40.868507
1282016,2015-11-06 23:49:57,2015-11-07 22:25:04,1355.116667,0.72,-73.940674,40.814255,-73.937485,40.822769
265911,2015-12-04 23:24:57,2015-12-05 22:59:34,1414.616667,0.74,-73.871056,40.752041,-73.878571,40.759819
1975770,2015-09-12 23:12:40,2015-09-13 22:47:23,1414.716667,0.82,-73.953262,40.807472,-73.958763,40.809792
1752715,2015-10-08 23:09:20,2015-10-09 22:51:06,1421.766667,1.01,-73.973587,40.752289,-73.987503,40.758862
1502248,2014-09-30 23:39:00,2014-10-01 22:44:46,1385.766667,1.04,-73.965584,40.693577,-73.983444,40.694401
759009,2015-06-30 23:03:14,2015-07-01 22:09:25,1386.183333,1.14,-73.994171,40.767281,-73.981888,40.778374
1291932,2015-10-11 23:00:27,2015-10-12 22:38:18,1417.850000,1.21,-73.954704,40.733376,-73.942520,40.725822
960738,2015-12-17 23:21:25,2015-12-18 22:33:06,1391.683333,1.23,-73.952141,40.798897,-73.940910,40.811722
1338816,2015-12-28 23:01:44,2015-12-29 22:51:19,1429.583333,1.25,-73.955368,40.714046,-73.955017,40.724380
1266751,2015-12-03 23:24:40,2015-12-04 22:29:32,1384.866667,1.27,-73.890793,40.746883,-73.877014,40.756275
1241955,2015-09-24 23:06:36,2015-09-25 22:13:41,1387.083333,1.35,-73.887131,40.749466,-73.865150,40.755798
971445,2015-11-30 23:17:41,2015-12-01 22:46:04,1408.383333,1.45,-73.957405,40.672153,-73.939194,40.671558
1451110,2014-06-28 23:01:59,2014-06-29 22:05:51,1383.866667,1.46,-73.879051,40.879490,-73.874832,40.896442
1157521,2014-07-30 23:04:43,2014-07-31 22:12:04,1387.350000,1.53,-73.939423,40.821346,-73.939377,40.805073
297256,2015-12-30 23:27:03,2015-12-31 22:40:01,1392.966667,1.53,-73.987106,40.694183,-73.964920,40.693619
1614922,2014-12-12 23:04:42,2014-12-13 22:58:54,1434.200000,1.54,-73.945648,40.807758,-73.965347,40.806061
363697,2014-09-11 23:33:33,2014-09-12 22:40:02,1386.483333,1.57,-73.957039,40.801991,-73.954842,40.819073
1901989,2015-10-23 23:05:57,2015-10-24 22:57:29,1431.533333,1.57,-73.912018,40.775192,-73.931801,40.768261
222265,2014-09-01 23:29:57,2014-09-02 22:36:21,1386.400000,1.71,-74.027061,40.633587,-74.004463,40.619652
282543,2015-04-08 23:20:32,2015-04-09 22:54:49,1414.283333,1.99,-73.986977,40.687729,-73.956421,40.674824
1428976,2014-10-04 23:45:44,2014-10-05 22:51:35,1385.850000,2.16,-73.992996,40.719704,-73.986732,40.722237
1218386,2015-04-01 23:01:20,2015-04-02 22:10:13,1388.883333,2.19,-73.942078,40.822739,-73.964989,40.804310
350700,2014-07-18 23:32:38,2014-07-19 22:51:28,1398.833333,2.24,-73.920181,40.835312,-73.900627,40.859856
1412296,2014-12-12 23:20:59,2014-12-13 22:53:48,1412.816667,2.29,-73.992317,40.689838,-74.013603,40.678627
1504987,2014-07-19 23:29:51,2014-07-20 22:40:59,1391.133333,2.36,-73.920753,40.756725,-73.879921,40.756496
149634,2015-09-19 23:02:40,2015-09-20 22:50:00,1427.333333,2.40,-73.829689,40.759682,-73.843323,40.784683
1040755,2015-06-09 23:31:51,2015-06-10 22:54:54,1403.050000,2.59,-73.844223,40.721443,-73.823738,40.698959
498833,2014-08-13 23:40:15,2014-08-14 22:44:13,1383.966667,2.71,-73.969215,40.693085,-73.932358,40.683811
1372295,2014-07-31 23:18:14,2014-08-01 22:18:15,1380.016667,2.72,-73.934685,40.796898,-73.940292,40.825039
665267,2015-09-03 23:33:17,2015-09-04 22:46:42,1393.416667,3.01,-73.884224,40.867882,-73.919487,40.852535
964465,2015-12-11 23:18:15,2015-12-12 22:53:46,1415.516667,3.11,-73.961021,40.632156,-74.003189,40.631321
1270818,2015-10-03 23:27:23,2015-10-04 22:58:06,1410.716667,3.12,-73.948143,40.724583,-73.901314,40.715107
1000107,2014-03-06 23:28:25,2014-03-07 22:57:18,1408.883333,3.20,-73.955704,40.719559,-73.954262,40.685341
209535,2015-10-06 23:31:02,2015-10-07 22:57:58,1406.933333,3.55,-73.956375,40.723331,-73.973000,40.689613
1372923,2014-05-26 23:08:29,2014-05-27 22:24:06,1395.616667,4.58,-73.951736,40.691628,-73.982590,40.731247
1639051,2014-08-17 23:16:42,2014-08-18 22:31:17,1394.583333,4.97,-73.945457,40.807789,-73.930267,40.866261
1332348,2015-10-13 23:11:40,2015-10-14 22:59:41,1428.016667,5.70,-73.951408,40.723698,-73.977592,40.747433
1585977,2014-03-19 23:27:20,2014-03-20 22:30:35,1383.250000,6.07,-73.870850,40.865334,-73.863617,40.881878
1318797,2014-10-19 23:19:34,2014-10-20 22:57:17,1417.716667,6.43,-73.913490,40.783264,-73.985260,40.778713
1410808,2014-07-06 23:00:43,2014-07-07 22:23:20,1402.616667,6.83,-73.813164,40.697308,-73.931564,40.680992
207980,2015-09-19 23:09:40,2015-09-20 22:52:44,1423.066667,9.97,-73.844398,40.721413,-73.994400,40.740417
1218094,2015-11-22 23:06:14,2015-11-23 22:59:34,1433.333333,14.14,-73.936424,40.849518,-73.941010,40.721661

In [167]:
mask6 = (pd.DatetimeIndex(df1['pickup_datetime_new']).hour > pd.DatetimeIndex(df1['dropoff_datetime_new']).hour) & (pd.DatetimeIndex(df1['dropoff_datetime_new']).hour > 21)
df1.loc[mask6, 'pickup_datetime_new'] = df1.loc[mask6, 'pickup_datetime_new'] - pd.Timedelta(hours=1) 
df1.loc[mask6, 'dropoff_datetime_new'] = df1.loc[mask6, 'dropoff_datetime_new'] - pd.Timedelta(days=1)

In [171]:
mask7 = (df.dropoff_datetime_new < df.pickup_datetime_new)
df1.loc[mask7, 'dropoff_datetime_new'] = df1.loc[mask7, 'dropoff_datetime_new'] + pd.Timedelta(days=1)

In [172]:
df1['travel_time'] = df1.dropoff_datetime_new - df1.pickup_datetime_new
df1.loc[:, 'travel_time'] = df1['travel_time'].dt.total_seconds() / 60

In [91]:
#subtract a day from the new pickup timestamp
df['pickup_datetime_new'] = np.where(df[mask3].index, (df['pickup_datetime_new']  - pd.Timedelta(days=1)), df['pickup_datetime_new'])

ValueError: operands could not be broadcast together with shapes (2666,) (1979173,) (1979173,)

In [175]:
df1[(df1['travel_time'] > 360)]

,pickup_datetime_new,dropoff_datetime_new,travel_time,trip_distance,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude
2889,2015-11-21 00:34:53,2015-11-22 00:14:34,1419.683333,0.66,-73.957748,40.730526,-73.957985,40.721672
9745,2015-10-04 00:05:11,2015-10-04 23:42:18,1417.116667,5.11,-73.936050,40.713085,-73.993599,40.696178
10093,2015-10-03 23:48:00,2015-10-04 23:44:20,1436.333333,13.59,-73.911797,40.775173,-73.925926,40.677418
11625,2015-12-30 23:25:15,2015-12-31 23:20:38,1435.383333,0.90,-73.937202,40.839634,-73.935577,40.850422
13094,2015-10-20 23:28:55,2015-10-21 23:24:43,1435.800000,1.19,-73.981384,40.675049,-73.963509,40.675686
15720,2015-03-12 00:17:48,2015-03-13 00:13:07,1435.316667,5.28,-73.915337,40.772575,-73.978310,40.744415
22834,2015-02-08 00:11:23,2015-02-08 23:33:53,1402.500000,3.16,-73.980598,40.688690,-73.923645,40.676949
34489,2015-05-07 00:32:26,2015-05-08 00:31:08,1438.700000,7.74,-73.957283,40.727009,-73.989990,40.746742
38089,2015-12-14 23:42:52,2015-12-15 23:23:25,1420.550000,3.74,-73.958214,40.721714,-73.990303,40.729610
42039,2015-03-27 14:00:07,2015-03-27 20:05:52,365.750000,33.66,-73.910889,40.658981,-73.832436,40.781593
43821,2015-09-11 00:41:33,2015-09-12 00:26:38,1425.083333,7.93,-73.964096,40.807945,-73.991890,40.722088
46749,2015-07-03 09:23:25,2015-07-03 15:46:24,382.983333,31.64,-73.754318,40.604904,-73.914032,40.585243
47545,2015-12-26 23:52:41,2015-12-27 23:32:58,1420.283333,0.81,-73.903519,40.745224,-73.899963,40.737514
50548,2015-10-09 00:20:06,2015-10-09 23:30:40,1390.566667,2.11,-73.956650,40.716858,-73.953323,40.691166
52641,2015-12-15 23:45:24,2015-12-16 23:31:43,1426.316667,2.08,-73.964508,40.683002,-73.959518,40.653992
53148,2015-09-30 00:01:07,2015-09-30 23:22:15,1401.133333,4.97,-73.957909,40.721813,-73.977531,40.744518
54055,2015-02-02 06:14:25,2015-02-02 15:25:25,551.000000,50.30,-73.993866,40.601784,-73.897423,40.609581
54704,2015-10-17 23:50:20,2015-10-18 23:16:47,1406.450000,1.29,-73.949211,40.802574,-73.939415,40.818291
56300,2015-06-13 00:14:51,2015-06-14 00:04:51,1430.000000,2.71,-73.922539,40.705666,-73.956024,40.693768
67780,2015-02-20 15:26:45,2015-02-20 23:59:23,512.633333,104.54,-74.000175,40.578709,-74.000252,40.578789
68587,2015-06-26 00:27:49,2015-06-27 00:23:52,1436.050000,1.21,-73.955444,40.640366,-73.950279,40.648888
70191,2015-11-03 00:02:46,2015-11-03 23:59:30,1436.733333,17.04,-73.887482,40.867935,-73.927010,40.738792
70894,2015-11-13 23:16:34,2015-11-14 23:08:23,1431.816667,3.50,-73.957893,40.721695,-73.963455,40.682846
73071,2015-10-07 00:31:09,2015-10-07 23:41:50,1390.683333,2.03,-73.978836,40.688133,-73.942139,40.687962
83242,2015-12-18 23:37:57,2015-12-19 23:31:24,1433.450000,3.01,-73.964874,40.715851,-73.955704,40.683380
89014,2015-09-13 00:50:42,2015-09-14 00:47:20,1436.633333,4.49,-73.929039,40.772026,-73.932846,40.799564
205546,2015-06-19 23:45:03,2015-06-20 23:30:56,1425.883333,8.68,-73.992760,40.697990,-74.035919,40.617031
207077,2015-06-01 23:21:23,2015-06-02 23:12:21,1430.966667,3.18,-73.960388,40.719635,-73.957939,40.686840
207439,2015-09-30 00:59:44,2015-10-01 00:07:36,1387.866667,2.52,-73.959213,40.708908,-73.921654,40.695938
216368,2014-06-07 00:04:16,2014-06-07 23:17:32,1393.266667,6.18,-74.000374,40.677872,-73.922058,40.690777
...,...,...,...,...,...,...,...,...
1731785,2015-10-20 00:36:13,2015-10-20 23:45:57,1389.733333,0.92,-74.007774,40.740597,-74.006378,40.733204
1733525,2015-10-17 00:28:02,2015-10-18 00:26:03,1438.016667,9.10,-73.986542,40.733902,-73.938911,40.822414
1745310,2015-11-21 23:14:55,2015-11-22 23:04:28,1429.550000,0.31,-73.982262,40.757286,-73.979279,40.759346
1759486,2015-08-13 00:27:50,2015-08-14 00:24:45,1436.916667,4.79,-73.988464,40.756603,-73.958992,40.809441
1760620,2015-05-02 23:59:15,2015-05-03 23:03:27,1384.200000,0.55,-73.943794,40.825439,-73.938156,40.822670
1805896,2015-11-15 00:47:56,2015-11-16 00:38:16,1430.333333,0.81,-73.989075,40.760288,-73.978470,40.762424
1808978,2015-04-26 23:03:38,2015-04-27 23:02:38,1439.000000,5.22,-73.950935,40.769669,-74.005707,40.741192
1810726,2015-12-04 23:21:02,2015-12-05 23:18:56,1437.900000,5.94,-73.973389,40.784889,-73.994987,40.726067
1811797,2015-02-21 00:25:14,2015-02-22 00:05:07,1419.883333,1.68,-73.937798,40.804585,-73.954201,40.787083
1824372,2015-09-11 00:07:50,2015-09-11 23:26:48,1398.966667,3.74,-73.990494,40.724880,-74.000229,40.760929
1833186,2015-09-17 00:39:57,2015-09-17 23:34:30,1374.550000,2.33,-74.010132,40.712204,-73.989960,40.731934
1838188,2015-02-28 23:47:26,2015-03-01 23:06:03,1398.616667,3.69,-73.950218,40.722786,-73.981461,40.730057
1838940,2015-12-16 23:39:52,2015-12-17 23:34:30,1434.633333,5.33,-73.948029,40.711319,-73.987991,40.667469
1841008,2015-12-05 00:28:53,2015-12-06 00:22:35,1433.700000,3.23,-73.983704,40.737965,-73.954590,40.778526
1843878,2015-12-09 23:10:58,2015-12-10 23:03:43,1432.750000,5.37,-74.000351,40.726440,-73.954384,40.781418
1882710,2015-10-30 00:44:42,2015-10-31 00:36:34,1431.866667,2.87,-73.986809,40.757668,-73.954567,40.769627
1910493,2015-11-13 23:57:54,2015-11-14 23:50:53,1432.983333,1.33,-73.897697,40.746059,-73.874809,40.743420
1912285,2015-09-19 00:50:36,2015-09-20 00:36:39,1426.050000,1.35,-73.953384,40.668659,-73.954323,40.684292
1918052,2015-09-28 23:49:14,2015-09-29 23:30:55,1421.683333,1.20,-73.961639,40.719402,-73.948952,40.727516
1926699,2015-10-30 23:19:22,2015-10-31 23:12:34,1433.200000,1.65,-73.952919,40.810940,-73.947395,40.830173
1927674,2015-10-07 23:08:34,2015-10-08 23:00:37,1432.050000,7.56,-73.892090,40.751041,-73.984703,40.701946
1932064,2015-10-10 23:55:41,2015-10-11 23:51:54,1436.216667,2.99,-73.959824,40.688911,-73.956055,40.650539
1959300,2015-05-30 23:49:03,2015-05-31 23:28:13,1419.166667,0.66,-73.890671,40.749043,-73.884789,40.744480
1963971,2015-09-25 23:16:13,2015-09-26 23:04:57,1428.733333,6.09,-73.969139,40.689522,-73.977654,40.733089
1964194,2015-12-29 00:10:14,2015-12-30 00:00:10,1429.933333,7.79,-73.891739,40.746872,-73.871529,40.673904
1982797,2015-03-20 17:26:59,2015-03-20 23:46:40,379.683333,26.05,-73.939415,40.810963,-73.953484,40.807114
1990357,2015-10-18 00:06:54,2015-10-18 23:37:45,1410.850000,3.02,-73.962524,40.712620,-73.983543,40.696190
1990525,2015-02-17 00:13:40,2015-02-18 00:11:17,1437.616667,7.51,-74.010277,40.655136,-74.009834,40.729809
1996565,2015-10-18 00:06:39,2015-10-19 00:00:29,1433.833333,2.18,-73.946671,40.717812,-73.920746,40.707539
1996600,2015-09-29 00:29:33,2015-09-29 22:16:27,1306.900000,1.80,-73.964096,40.808048,-73.977188,40.785275

In [177]:
# for now, eliminate rows trying to fix in previous two lines
df = df[(df['travel_time'] < 360)]

In [178]:
#recalculate travel time
df['travel_time_new'] = df.dropoff_datetime_new - df.pickup_datetime_new
df['travel_time_new'] = df['travel_time_new'].dt.total_seconds()
df['pickup_datetime_new'] = pd.DatetimeIndex(df['pickup_datetime_new']).round('min')

In [191]:
df = df[df['travel_time_new'] != 0]

In [176]:
graph_df = df1[['pickup_longitude', 'pickup_latitude']]
geometry = [Point(xy) for xy in zip(graph_df.pickup_longitude, graph_df.pickup_latitude)]
graph_df = GeoDataFrame(graph_df, geometry=geometry)

In [177]:
shape = gpd.read_file("C:/Users/Stevens/Desktop/BIA 674/Project/tl_2016_36_tabblock10/tl_2016_36_tabblock10.shp")
shape['centroid_column'] = shape.centroid
nyc_counties = ['061', '081', '047', '005', '085']
shape = shape[shape['COUNTYFP10'].isin(nyc_counties)]

In [178]:
data = gpd.sjoin(graph_df, shape, how="inner", op='intersects')

Warning: CRS does not match!

KeyboardInterrupt:

In [195]:
graph_df2 = df1[['dropoff_longitude', 'dropoff_latitude']]
geometry = [Point(xy) for xy in zip(graph_df2.dropoff_longitude, graph_df2.dropoff_latitude)]
graph_df2 = GeoDataFrame(graph_df2, geometry=geometry)

In [196]:
data2 = gpd.sjoin(graph_df2, shape, how="inner", op='intersects')

Warning: CRS does not match!

In [197]:
pickup_block = pd.DataFrame(data['centroid_column'])
dropoff_block = pd.DataFrame(data2['centroid_column'])

In [198]:
pickup_block.columns = ['pickup_block']
dropoff_block.columns = ['dropoff_block']

In [213]:
dataframes = [pd.DataFrame(pickup_block.reset_index().pickup_block), pd.DataFrame(dropoff_block.reset_index().dropoff_block), df[['pickup_datetime_new', 'travel_time_new', 'trip_distance']]]
df_final = functools.reduce(lambda left,right: pd.merge(left, right, how='inner', left_index=True, right_index=True), dataframes)

In [214]:
df_final = df_final.assign(
    tod=pd.cut(
        df_final.pickup_datetime_new.dt.hour,
        [0, 6, 8, 15, 18, 24],
        labels=['night', 'rush_am', 'midday', 'rush_pm', 'evening']))

In [215]:
df_final.to_csv('C:/Users/Stevens/Desktop/BIA 674/Project/data.csv')